# Generated by Django 2.1.5 on 2019-02-08 11:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20150515_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='jid',
            field=models.CharField(help_text='Required, a confirmation message will be sent to this address.', max_length=128),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
